[package]
name = "weight4me"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rsdd = { path = "../rsdd" }
nalgebra = "0.30.1"
itertools = "0.10.3"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-test = "0.2.4"
