#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 98
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 53
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  sym_tBool = 4,
  anon_sym_COMMA = 5,
  anon_sym_fst = 6,
  anon_sym_snd = 7,
  anon_sym_prj = 8,
  sym_index = 9,
  anon_sym_let = 10,
  anon_sym_EQ = 11,
  anon_sym_in = 12,
  anon_sym_COLON = 13,
  anon_sym_if = 14,
  anon_sym_then = 15,
  anon_sym_else = 16,
  anon_sym_flip = 17,
  anon_sym_observe = 18,
  anon_sym_sample = 19,
  anon_sym_true = 20,
  anon_sym_false = 21,
  anon_sym_PIPE_PIPE = 22,
  anon_sym_AMP_AMP = 23,
  sym_bool_unop = 24,
  sym_float = 25,
  anon_sym_STAR = 26,
  anon_sym_SLASH = 27,
  anon_sym_PLUS = 28,
  anon_sym_DASH = 29,
  sym_source_file = 30,
  sym__expr = 31,
  sym_ty = 32,
  sym_tProd = 33,
  sym_fst = 34,
  sym_snd = 35,
  sym_prj = 36,
  sym_prod = 37,
  sym_let_binding = 38,
  sym_ite_binding = 39,
  sym_flip = 40,
  sym_observe = 41,
  sym_sample = 42,
  sym_bool = 43,
  sym_bool_biop = 44,
  sym__float = 45,
  sym_float_op = 46,
  sym__value = 47,
  sym_ann = 48,
  sym_anf = 49,
  aux_sym_tProd_repeat1 = 50,
  aux_sym_prod_repeat1 = 51,
  aux_sym__value_repeat1 = 52,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_tBool] = "tBool",
  [anon_sym_COMMA] = ",",
  [anon_sym_fst] = "fst",
  [anon_sym_snd] = "snd",
  [anon_sym_prj] = "prj",
  [sym_index] = "index",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_in] = "in",
  [anon_sym_COLON] = ":",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_flip] = "flip",
  [anon_sym_observe] = "observe",
  [anon_sym_sample] = "sample",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [sym_bool_unop] = "bool_unop",
  [sym_float] = "float",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_ty] = "ty",
  [sym_tProd] = "tProd",
  [sym_fst] = "fst",
  [sym_snd] = "snd",
  [sym_prj] = "prj",
  [sym_prod] = "prod",
  [sym_let_binding] = "let_binding",
  [sym_ite_binding] = "ite_binding",
  [sym_flip] = "flip",
  [sym_observe] = "observe",
  [sym_sample] = "sample",
  [sym_bool] = "bool",
  [sym_bool_biop] = "bool_biop",
  [sym__float] = "_float",
  [sym_float_op] = "float_op",
  [sym__value] = "_value",
  [sym_ann] = "ann",
  [sym_anf] = "anf",
  [aux_sym_tProd_repeat1] = "tProd_repeat1",
  [aux_sym_prod_repeat1] = "prod_repeat1",
  [aux_sym__value_repeat1] = "_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_tBool] = sym_tBool,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_fst] = anon_sym_fst,
  [anon_sym_snd] = anon_sym_snd,
  [anon_sym_prj] = anon_sym_prj,
  [sym_index] = sym_index,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_flip] = anon_sym_flip,
  [anon_sym_observe] = anon_sym_observe,
  [anon_sym_sample] = anon_sym_sample,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [sym_bool_unop] = sym_bool_unop,
  [sym_float] = sym_float,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_ty] = sym_ty,
  [sym_tProd] = sym_tProd,
  [sym_fst] = sym_fst,
  [sym_snd] = sym_snd,
  [sym_prj] = sym_prj,
  [sym_prod] = sym_prod,
  [sym_let_binding] = sym_let_binding,
  [sym_ite_binding] = sym_ite_binding,
  [sym_flip] = sym_flip,
  [sym_observe] = sym_observe,
  [sym_sample] = sym_sample,
  [sym_bool] = sym_bool,
  [sym_bool_biop] = sym_bool_biop,
  [sym__float] = sym__float,
  [sym_float_op] = sym_float_op,
  [sym__value] = sym__value,
  [sym_ann] = sym_ann,
  [sym_anf] = sym_anf,
  [aux_sym_tProd_repeat1] = aux_sym_tProd_repeat1,
  [aux_sym_prod_repeat1] = aux_sym_prod_repeat1,
  [aux_sym__value_repeat1] = aux_sym__value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_tBool] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fst] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_snd] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_prj] = {
    .visible = true,
    .named = false,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_observe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sample] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_bool_unop] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_ty] = {
    .visible = true,
    .named = true,
  },
  [sym_tProd] = {
    .visible = true,
    .named = true,
  },
  [sym_fst] = {
    .visible = true,
    .named = true,
  },
  [sym_snd] = {
    .visible = true,
    .named = true,
  },
  [sym_prj] = {
    .visible = true,
    .named = true,
  },
  [sym_prod] = {
    .visible = true,
    .named = true,
  },
  [sym_let_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_ite_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_flip] = {
    .visible = true,
    .named = true,
  },
  [sym_observe] = {
    .visible = true,
    .named = true,
  },
  [sym_sample] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_biop] = {
    .visible = true,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym_float_op] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_ann] = {
    .visible = true,
    .named = true,
  },
  [sym_anf] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tProd_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prod_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '!') ADVANCE(15);
      if (lookahead == '&') ADVANCE(1);
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == ')') ADVANCE(7);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '+') ADVANCE(20);
      if (lookahead == ',') ADVANCE(8);
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == ':') ADVANCE(12);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '|') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '&') ADVANCE(14);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == '|') ADVANCE(13);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_index);
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_index);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_bool_unop);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'B') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'o') ADVANCE(6);
      if (lookahead == 'p') ADVANCE(7);
      if (lookahead == 's') ADVANCE(8);
      if (lookahead == 't') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(12);
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(20);
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(22);
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'j') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(33);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(35);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 26:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(39);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_fst);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_prj);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_snd);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_tBool);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_flip);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 45:
      if (lookahead == 'v') ADVANCE(47);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_sample);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_observe);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 3},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_tBool] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_fst] = ACTIONS(1),
    [anon_sym_snd] = ACTIONS(1),
    [anon_sym_prj] = ACTIONS(1),
    [sym_index] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_flip] = ACTIONS(1),
    [anon_sym_observe] = ACTIONS(1),
    [anon_sym_sample] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [sym_bool_unop] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(94),
    [sym__expr] = STATE(73),
    [sym_fst] = STATE(73),
    [sym_snd] = STATE(73),
    [sym_prj] = STATE(73),
    [sym_prod] = STATE(73),
    [sym_let_binding] = STATE(73),
    [sym_ite_binding] = STATE(73),
    [sym_flip] = STATE(73),
    [sym_observe] = STATE(73),
    [sym_sample] = STATE(73),
    [sym_bool] = STATE(15),
    [sym__value] = STATE(15),
    [sym_ann] = STATE(73),
    [sym_anf] = STATE(32),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fst] = ACTIONS(7),
    [anon_sym_snd] = ACTIONS(9),
    [anon_sym_prj] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_observe] = ACTIONS(19),
    [anon_sym_sample] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_bool_unop] = ACTIONS(25),
  },
  [2] = {
    [sym__expr] = STATE(45),
    [sym_fst] = STATE(45),
    [sym_snd] = STATE(45),
    [sym_prj] = STATE(45),
    [sym_prod] = STATE(45),
    [sym_let_binding] = STATE(45),
    [sym_ite_binding] = STATE(45),
    [sym_flip] = STATE(45),
    [sym_observe] = STATE(45),
    [sym_sample] = STATE(45),
    [sym_bool] = STATE(15),
    [sym__value] = STATE(15),
    [sym_ann] = STATE(45),
    [sym_anf] = STATE(32),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fst] = ACTIONS(7),
    [anon_sym_snd] = ACTIONS(9),
    [anon_sym_prj] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_observe] = ACTIONS(19),
    [anon_sym_sample] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_bool_unop] = ACTIONS(25),
  },
  [3] = {
    [sym__expr] = STATE(82),
    [sym_fst] = STATE(82),
    [sym_snd] = STATE(82),
    [sym_prj] = STATE(82),
    [sym_prod] = STATE(82),
    [sym_let_binding] = STATE(82),
    [sym_ite_binding] = STATE(82),
    [sym_flip] = STATE(82),
    [sym_observe] = STATE(82),
    [sym_sample] = STATE(82),
    [sym_bool] = STATE(46),
    [sym__value] = STATE(46),
    [sym_ann] = STATE(82),
    [sym_anf] = STATE(37),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fst] = ACTIONS(7),
    [anon_sym_snd] = ACTIONS(9),
    [anon_sym_prj] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_observe] = ACTIONS(19),
    [anon_sym_sample] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_bool_unop] = ACTIONS(25),
  },
  [4] = {
    [sym__expr] = STATE(81),
    [sym_fst] = STATE(81),
    [sym_snd] = STATE(81),
    [sym_prj] = STATE(81),
    [sym_prod] = STATE(81),
    [sym_let_binding] = STATE(81),
    [sym_ite_binding] = STATE(81),
    [sym_flip] = STATE(81),
    [sym_observe] = STATE(81),
    [sym_sample] = STATE(81),
    [sym_bool] = STATE(15),
    [sym__value] = STATE(15),
    [sym_ann] = STATE(81),
    [sym_anf] = STATE(32),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fst] = ACTIONS(7),
    [anon_sym_snd] = ACTIONS(9),
    [anon_sym_prj] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_observe] = ACTIONS(19),
    [anon_sym_sample] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_bool_unop] = ACTIONS(25),
  },
  [5] = {
    [sym__expr] = STATE(80),
    [sym_fst] = STATE(80),
    [sym_snd] = STATE(80),
    [sym_prj] = STATE(80),
    [sym_prod] = STATE(80),
    [sym_let_binding] = STATE(80),
    [sym_ite_binding] = STATE(80),
    [sym_flip] = STATE(80),
    [sym_observe] = STATE(80),
    [sym_sample] = STATE(80),
    [sym_bool] = STATE(15),
    [sym__value] = STATE(15),
    [sym_ann] = STATE(80),
    [sym_anf] = STATE(32),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fst] = ACTIONS(7),
    [anon_sym_snd] = ACTIONS(9),
    [anon_sym_prj] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_observe] = ACTIONS(19),
    [anon_sym_sample] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_bool_unop] = ACTIONS(25),
  },
  [6] = {
    [sym__expr] = STATE(84),
    [sym_fst] = STATE(84),
    [sym_snd] = STATE(84),
    [sym_prj] = STATE(84),
    [sym_prod] = STATE(84),
    [sym_let_binding] = STATE(84),
    [sym_ite_binding] = STATE(84),
    [sym_flip] = STATE(84),
    [sym_observe] = STATE(84),
    [sym_sample] = STATE(84),
    [sym_bool] = STATE(15),
    [sym__value] = STATE(15),
    [sym_ann] = STATE(84),
    [sym_anf] = STATE(32),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fst] = ACTIONS(7),
    [anon_sym_snd] = ACTIONS(9),
    [anon_sym_prj] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_observe] = ACTIONS(19),
    [anon_sym_sample] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_bool_unop] = ACTIONS(25),
  },
  [7] = {
    [sym__expr] = STATE(49),
    [sym_fst] = STATE(49),
    [sym_snd] = STATE(49),
    [sym_prj] = STATE(49),
    [sym_prod] = STATE(49),
    [sym_let_binding] = STATE(49),
    [sym_ite_binding] = STATE(49),
    [sym_flip] = STATE(49),
    [sym_observe] = STATE(49),
    [sym_sample] = STATE(49),
    [sym_bool] = STATE(15),
    [sym__value] = STATE(15),
    [sym_ann] = STATE(49),
    [sym_anf] = STATE(32),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fst] = ACTIONS(7),
    [anon_sym_snd] = ACTIONS(9),
    [anon_sym_prj] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_observe] = ACTIONS(19),
    [anon_sym_sample] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_bool_unop] = ACTIONS(25),
  },
  [8] = {
    [sym__expr] = STATE(76),
    [sym_fst] = STATE(76),
    [sym_snd] = STATE(76),
    [sym_prj] = STATE(76),
    [sym_prod] = STATE(76),
    [sym_let_binding] = STATE(76),
    [sym_ite_binding] = STATE(76),
    [sym_flip] = STATE(76),
    [sym_observe] = STATE(76),
    [sym_sample] = STATE(76),
    [sym_bool] = STATE(15),
    [sym__value] = STATE(15),
    [sym_ann] = STATE(76),
    [sym_anf] = STATE(32),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fst] = ACTIONS(7),
    [anon_sym_snd] = ACTIONS(9),
    [anon_sym_prj] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_observe] = ACTIONS(19),
    [anon_sym_sample] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_bool_unop] = ACTIONS(25),
  },
  [9] = {
    [sym__expr] = STATE(60),
    [sym_fst] = STATE(60),
    [sym_snd] = STATE(60),
    [sym_prj] = STATE(60),
    [sym_prod] = STATE(60),
    [sym_let_binding] = STATE(60),
    [sym_ite_binding] = STATE(60),
    [sym_flip] = STATE(60),
    [sym_observe] = STATE(60),
    [sym_sample] = STATE(60),
    [sym_bool] = STATE(15),
    [sym__value] = STATE(15),
    [sym_ann] = STATE(60),
    [sym_anf] = STATE(32),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_fst] = ACTIONS(7),
    [anon_sym_snd] = ACTIONS(9),
    [anon_sym_prj] = ACTIONS(11),
    [anon_sym_let] = ACTIONS(13),
    [anon_sym_if] = ACTIONS(15),
    [anon_sym_flip] = ACTIONS(17),
    [anon_sym_observe] = ACTIONS(19),
    [anon_sym_sample] = ACTIONS(21),
    [anon_sym_true] = ACTIONS(23),
    [anon_sym_false] = ACTIONS(23),
    [sym_bool_unop] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(27), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [15] = 2,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(29), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [30] = 3,
    STATE(90), 1,
      sym_float_op,
    ACTIONS(33), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [47] = 1,
    ACTIONS(35), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [59] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      aux_sym_prod_repeat1,
    STATE(51), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [83] = 1,
    ACTIONS(39), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [95] = 7,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(14), 1,
      aux_sym_prod_repeat1,
    STATE(56), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [119] = 1,
    ACTIONS(41), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [131] = 7,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(46), 1,
      anon_sym_LPAREN,
    ACTIONS(52), 1,
      sym_bool_unop,
    STATE(18), 1,
      aux_sym_prod_repeat1,
    STATE(68), 1,
      sym_anf,
    ACTIONS(49), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [155] = 1,
    ACTIONS(55), 9,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [167] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [188] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(10), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [209] = 3,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(57), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [224] = 3,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(61), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [239] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(67), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [260] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [281] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(63), 1,
      anon_sym_LPAREN,
    STATE(28), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [302] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(62), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 2,
      sym_bool,
      sym__value,
  [323] = 3,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(65), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [338] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(63), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [359] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [380] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(25), 1,
      sym_bool_unop,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym_anf,
    ACTIONS(23), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_bool,
      sym__value,
  [401] = 3,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(67), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [416] = 3,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(69), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [431] = 1,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [441] = 1,
    ACTIONS(73), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [451] = 1,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [461] = 4,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(67), 2,
      anon_sym_RPAREN,
      anon_sym_COLON,
  [476] = 4,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(39), 1,
      aux_sym__value_repeat1,
    ACTIONS(79), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(75), 2,
      sym_bool,
      sym__value,
  [491] = 4,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    STATE(39), 1,
      aux_sym__value_repeat1,
    ACTIONS(84), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(91), 2,
      sym_bool,
      sym__value,
  [506] = 4,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      aux_sym__value_repeat1,
    ACTIONS(79), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(74), 2,
      sym_bool,
      sym__value,
  [521] = 5,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_tBool,
    STATE(36), 1,
      sym_tProd,
    STATE(44), 1,
      aux_sym_tProd_repeat1,
    STATE(77), 1,
      sym_ty,
  [537] = 1,
    ACTIONS(91), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [545] = 1,
    ACTIONS(93), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [553] = 5,
    ACTIONS(95), 1,
      anon_sym_LPAREN,
    ACTIONS(98), 1,
      sym_tBool,
    STATE(36), 1,
      sym_tProd,
    STATE(44), 1,
      aux_sym_tProd_repeat1,
    STATE(97), 1,
      sym_ty,
  [569] = 2,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_else,
  [579] = 2,
    ACTIONS(105), 1,
      anon_sym_COMMA,
    ACTIONS(39), 4,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [589] = 1,
    ACTIONS(107), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [597] = 1,
    ACTIONS(109), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [605] = 2,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(111), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_else,
  [615] = 5,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_tBool,
    STATE(36), 1,
      sym_tProd,
    STATE(41), 1,
      aux_sym_tProd_repeat1,
    STATE(83), 1,
      sym_ty,
  [631] = 4,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [645] = 2,
    ACTIONS(119), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(117), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [655] = 1,
    ACTIONS(121), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [663] = 2,
    ACTIONS(125), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(123), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [673] = 1,
    ACTIONS(127), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [681] = 4,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [695] = 1,
    ACTIONS(131), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [703] = 1,
    ACTIONS(133), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [711] = 1,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_COLON,
      anon_sym_else,
  [719] = 2,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(137), 4,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_in,
      anon_sym_else,
  [729] = 3,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(79), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(87), 2,
      sym_bool,
      sym__value,
  [741] = 3,
    ACTIONS(139), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [752] = 3,
    ACTIONS(141), 1,
      anon_sym_then,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [763] = 4,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_tBool,
    STATE(36), 1,
      sym_tProd,
    STATE(93), 1,
      sym_ty,
  [776] = 4,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_tBool,
    STATE(36), 1,
      sym_tProd,
    STATE(53), 1,
      sym_ty,
  [789] = 4,
    ACTIONS(87), 1,
      anon_sym_LPAREN,
    ACTIONS(89), 1,
      sym_tBool,
    STATE(36), 1,
      sym_tProd,
    STATE(92), 1,
      sym_ty,
  [802] = 3,
    ACTIONS(143), 1,
      anon_sym_RPAREN,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [813] = 3,
    ACTIONS(115), 1,
      anon_sym_COMMA,
    STATE(30), 1,
      sym_bool_biop,
    ACTIONS(59), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [824] = 1,
    ACTIONS(145), 3,
      anon_sym_LPAREN,
      anon_sym_true,
      anon_sym_false,
  [830] = 3,
    ACTIONS(147), 1,
      anon_sym_LPAREN,
    ACTIONS(149), 1,
      sym_float,
    STATE(86), 1,
      sym__float,
  [840] = 3,
    ACTIONS(147), 1,
      anon_sym_LPAREN,
    ACTIONS(149), 1,
      sym_float,
    STATE(55), 1,
      sym__float,
  [850] = 2,
    ACTIONS(151), 1,
      anon_sym_EQ,
    ACTIONS(153), 1,
      anon_sym_COLON,
  [857] = 2,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
  [864] = 2,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    ACTIONS(159), 1,
      anon_sym_COMMA,
  [871] = 2,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_RPAREN,
  [878] = 2,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(163), 1,
      anon_sym_in,
  [885] = 2,
    ACTIONS(165), 1,
      anon_sym_RPAREN,
    ACTIONS(167), 1,
      anon_sym_COMMA,
  [892] = 1,
    ACTIONS(169), 2,
      anon_sym_LPAREN,
      sym_tBool,
  [897] = 2,
    ACTIONS(171), 1,
      anon_sym_LPAREN,
    ACTIONS(173), 1,
      sym_index,
  [904] = 2,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
  [911] = 2,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(177), 1,
      anon_sym_else,
  [918] = 2,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
  [925] = 2,
    ACTIONS(167), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
  [932] = 2,
    ACTIONS(103), 1,
      anon_sym_COLON,
    ACTIONS(183), 1,
      anon_sym_in,
  [939] = 1,
    ACTIONS(185), 1,
      anon_sym_COMMA,
  [943] = 1,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
  [947] = 1,
    ACTIONS(105), 1,
      anon_sym_COMMA,
  [951] = 1,
    ACTIONS(189), 1,
      sym_float,
  [955] = 1,
    ACTIONS(191), 1,
      sym_index,
  [959] = 1,
    ACTIONS(187), 1,
      sym_float,
  [963] = 1,
    ACTIONS(159), 1,
      anon_sym_COMMA,
  [967] = 1,
    ACTIONS(193), 1,
      anon_sym_COMMA,
  [971] = 1,
    ACTIONS(195), 1,
      anon_sym_EQ,
  [975] = 1,
    ACTIONS(197), 1,
      ts_builtin_sym_end,
  [979] = 1,
    ACTIONS(199), 1,
      anon_sym_LPAREN,
  [983] = 1,
    ACTIONS(201), 1,
      sym_identifier,
  [987] = 1,
    ACTIONS(167), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 15,
  [SMALL_STATE(12)] = 30,
  [SMALL_STATE(13)] = 47,
  [SMALL_STATE(14)] = 59,
  [SMALL_STATE(15)] = 83,
  [SMALL_STATE(16)] = 95,
  [SMALL_STATE(17)] = 119,
  [SMALL_STATE(18)] = 131,
  [SMALL_STATE(19)] = 155,
  [SMALL_STATE(20)] = 167,
  [SMALL_STATE(21)] = 188,
  [SMALL_STATE(22)] = 209,
  [SMALL_STATE(23)] = 224,
  [SMALL_STATE(24)] = 239,
  [SMALL_STATE(25)] = 260,
  [SMALL_STATE(26)] = 281,
  [SMALL_STATE(27)] = 302,
  [SMALL_STATE(28)] = 323,
  [SMALL_STATE(29)] = 338,
  [SMALL_STATE(30)] = 359,
  [SMALL_STATE(31)] = 380,
  [SMALL_STATE(32)] = 401,
  [SMALL_STATE(33)] = 416,
  [SMALL_STATE(34)] = 431,
  [SMALL_STATE(35)] = 441,
  [SMALL_STATE(36)] = 451,
  [SMALL_STATE(37)] = 461,
  [SMALL_STATE(38)] = 476,
  [SMALL_STATE(39)] = 491,
  [SMALL_STATE(40)] = 506,
  [SMALL_STATE(41)] = 521,
  [SMALL_STATE(42)] = 537,
  [SMALL_STATE(43)] = 545,
  [SMALL_STATE(44)] = 553,
  [SMALL_STATE(45)] = 569,
  [SMALL_STATE(46)] = 579,
  [SMALL_STATE(47)] = 589,
  [SMALL_STATE(48)] = 597,
  [SMALL_STATE(49)] = 605,
  [SMALL_STATE(50)] = 615,
  [SMALL_STATE(51)] = 631,
  [SMALL_STATE(52)] = 645,
  [SMALL_STATE(53)] = 655,
  [SMALL_STATE(54)] = 663,
  [SMALL_STATE(55)] = 673,
  [SMALL_STATE(56)] = 681,
  [SMALL_STATE(57)] = 695,
  [SMALL_STATE(58)] = 703,
  [SMALL_STATE(59)] = 711,
  [SMALL_STATE(60)] = 719,
  [SMALL_STATE(61)] = 729,
  [SMALL_STATE(62)] = 741,
  [SMALL_STATE(63)] = 752,
  [SMALL_STATE(64)] = 763,
  [SMALL_STATE(65)] = 776,
  [SMALL_STATE(66)] = 789,
  [SMALL_STATE(67)] = 802,
  [SMALL_STATE(68)] = 813,
  [SMALL_STATE(69)] = 824,
  [SMALL_STATE(70)] = 830,
  [SMALL_STATE(71)] = 840,
  [SMALL_STATE(72)] = 850,
  [SMALL_STATE(73)] = 857,
  [SMALL_STATE(74)] = 864,
  [SMALL_STATE(75)] = 871,
  [SMALL_STATE(76)] = 878,
  [SMALL_STATE(77)] = 885,
  [SMALL_STATE(78)] = 892,
  [SMALL_STATE(79)] = 897,
  [SMALL_STATE(80)] = 904,
  [SMALL_STATE(81)] = 911,
  [SMALL_STATE(82)] = 918,
  [SMALL_STATE(83)] = 925,
  [SMALL_STATE(84)] = 932,
  [SMALL_STATE(85)] = 939,
  [SMALL_STATE(86)] = 943,
  [SMALL_STATE(87)] = 947,
  [SMALL_STATE(88)] = 951,
  [SMALL_STATE(89)] = 955,
  [SMALL_STATE(90)] = 959,
  [SMALL_STATE(91)] = 963,
  [SMALL_STATE(92)] = 967,
  [SMALL_STATE(93)] = 971,
  [SMALL_STATE(94)] = 975,
  [SMALL_STATE(95)] = 979,
  [SMALL_STATE(96)] = 983,
  [SMALL_STATE(97)] = 987,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anf, 2),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anf, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 5),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anf, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 6),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prod_repeat1, 2), SHIFT_REPEAT(15),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prod_repeat1, 2), SHIFT_REPEAT(61),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prod_repeat1, 2), SHIFT_REPEAT(19),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prod_repeat1, 2), SHIFT_REPEAT(21),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fst, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snd, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observe, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prj, 3),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tProd, 5),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tProd, 6),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ty, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__value_repeat1, 2), SHIFT_REPEAT(61),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__value_repeat1, 2), SHIFT_REPEAT(19),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prod, 5),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prj, 6),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tProd_repeat1, 2), SHIFT_REPEAT(66),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tProd_repeat1, 2), SHIFT_REPEAT(36),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 8),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prod, 6),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 3),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 6),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool_biop, 1),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_biop, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ann, 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_prod_repeat1, 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prod_repeat1, 2),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flip, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observe, 4),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 4),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ite_binding, 6),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__value_repeat1, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tProd_repeat1, 2),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_op, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [197] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_yodel(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
