#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  anon_sym_fst = 2,
  anon_sym_snd = 3,
  anon_sym_LPAREN = 4,
  anon_sym_COMMA = 5,
  anon_sym_RPAREN = 6,
  anon_sym_let = 7,
  anon_sym_EQ = 8,
  anon_sym_in = 9,
  anon_sym_if = 10,
  anon_sym_then = 11,
  anon_sym_else = 12,
  anon_sym_flip = 13,
  anon_sym_observe = 14,
  anon_sym_sample = 15,
  anon_sym_true = 16,
  anon_sym_false = 17,
  anon_sym_PIPE_PIPE = 18,
  anon_sym_AMP_AMP = 19,
  sym_bool_unop = 20,
  sym_float = 21,
  anon_sym_STAR = 22,
  anon_sym_SLASH = 23,
  anon_sym_PLUS = 24,
  anon_sym_DASH = 25,
  sym_source_file = 26,
  sym__expr = 27,
  sym_let_binding = 28,
  sym_ite_binding = 29,
  sym_flip = 30,
  sym_observe = 31,
  sym_sample = 32,
  sym_bool = 33,
  sym_bool_biop = 34,
  sym__float = 35,
  sym_float_op = 36,
  sym__value = 37,
  sym_anf = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_fst] = "fst",
  [anon_sym_snd] = "snd",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_in] = "in",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_flip] = "flip",
  [anon_sym_observe] = "observe",
  [anon_sym_sample] = "sample",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [sym_bool_unop] = "bool_unop",
  [sym_float] = "float",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_let_binding] = "let_binding",
  [sym_ite_binding] = "ite_binding",
  [sym_flip] = "flip",
  [sym_observe] = "observe",
  [sym_sample] = "sample",
  [sym_bool] = "bool",
  [sym_bool_biop] = "bool_biop",
  [sym__float] = "_float",
  [sym_float_op] = "float_op",
  [sym__value] = "_value",
  [sym_anf] = "anf",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_fst] = anon_sym_fst,
  [anon_sym_snd] = anon_sym_snd,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_flip] = anon_sym_flip,
  [anon_sym_observe] = anon_sym_observe,
  [anon_sym_sample] = anon_sym_sample,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [sym_bool_unop] = sym_bool_unop,
  [sym_float] = sym_float,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_let_binding] = sym_let_binding,
  [sym_ite_binding] = sym_ite_binding,
  [sym_flip] = sym_flip,
  [sym_observe] = sym_observe,
  [sym_sample] = sym_sample,
  [sym_bool] = sym_bool,
  [sym_bool_biop] = sym_bool_biop,
  [sym__float] = sym__float,
  [sym_float_op] = sym_float_op,
  [sym__value] = sym__value,
  [sym_anf] = sym_anf,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fst] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_snd] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_observe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sample] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_bool_unop] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_let_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_ite_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_flip] = {
    .visible = true,
    .named = true,
  },
  [sym_observe] = {
    .visible = true,
    .named = true,
  },
  [sym_sample] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_biop] = {
    .visible = true,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym_float_op] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_anf] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 5,
  [9] = 7,
  [10] = 10,
  [11] = 6,
  [12] = 4,
  [13] = 10,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 14,
  [31] = 17,
  [32] = 32,
  [33] = 32,
  [34] = 16,
  [35] = 35,
  [36] = 35,
  [37] = 37,
  [38] = 37,
  [39] = 39,
  [40] = 40,
  [41] = 21,
  [42] = 42,
  [43] = 20,
  [44] = 40,
  [45] = 45,
  [46] = 46,
  [47] = 42,
  [48] = 39,
  [49] = 45,
  [50] = 46,
  [51] = 19,
  [52] = 15,
  [53] = 18,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 56,
  [59] = 57,
  [60] = 60,
  [61] = 60,
  [62] = 55,
  [63] = 23,
  [64] = 64,
  [65] = 24,
  [66] = 29,
  [67] = 28,
  [68] = 27,
  [69] = 26,
  [70] = 25,
  [71] = 71,
  [72] = 71,
  [73] = 22,
  [74] = 64,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 77,
  [85] = 80,
  [86] = 83,
  [87] = 78,
  [88] = 81,
  [89] = 89,
  [90] = 82,
  [91] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '!') ADVANCE(10);
      if (lookahead == '&') ADVANCE(1);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == '*') ADVANCE(13);
      if (lookahead == '+') ADVANCE(15);
      if (lookahead == ',') ADVANCE(5);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == '=') ADVANCE(7);
      if (lookahead == '|') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '&') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '|') ADVANCE(8);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_bool_unop);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'o') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(9);
      if (lookahead == 'l') ADVANCE(10);
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 'b') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'h') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'm') ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead == 'p') ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_fst);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_snd);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_flip);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 38:
      if (lookahead == 'v') ADVANCE(40);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_sample);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_observe);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_fst] = ACTIONS(1),
    [anon_sym_snd] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_flip] = ACTIONS(1),
    [anon_sym_observe] = ACTIONS(1),
    [anon_sym_sample] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [sym_bool_unop] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(76),
    [sym__expr] = STATE(75),
    [sym_let_binding] = STATE(75),
    [sym_ite_binding] = STATE(75),
    [sym_flip] = STATE(75),
    [sym_observe] = STATE(75),
    [sym_sample] = STATE(75),
    [sym_bool] = STATE(43),
    [sym__value] = STATE(43),
    [sym_anf] = STATE(51),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
  [2] = {
    [sym__expr] = STATE(28),
    [sym_let_binding] = STATE(28),
    [sym_ite_binding] = STATE(28),
    [sym_flip] = STATE(28),
    [sym_observe] = STATE(28),
    [sym_sample] = STATE(28),
    [sym_bool] = STATE(20),
    [sym__value] = STATE(20),
    [sym_anf] = STATE(19),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_fst] = ACTIONS(25),
    [anon_sym_snd] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_in] = ACTIONS(31),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_flip] = ACTIONS(35),
    [anon_sym_observe] = ACTIONS(37),
    [anon_sym_sample] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [sym_bool_unop] = ACTIONS(43),
  },
  [3] = {
    [sym__expr] = STATE(67),
    [sym_let_binding] = STATE(67),
    [sym_ite_binding] = STATE(67),
    [sym_flip] = STATE(67),
    [sym_observe] = STATE(67),
    [sym_sample] = STATE(67),
    [sym_bool] = STATE(43),
    [sym__value] = STATE(43),
    [sym_anf] = STATE(51),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_in] = ACTIONS(45),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
  [4] = {
    [sym__expr] = STATE(84),
    [sym_let_binding] = STATE(84),
    [sym_ite_binding] = STATE(84),
    [sym_flip] = STATE(84),
    [sym_observe] = STATE(84),
    [sym_sample] = STATE(84),
    [sym_bool] = STATE(43),
    [sym__value] = STATE(43),
    [sym_anf] = STATE(51),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
  [5] = {
    [sym__expr] = STATE(79),
    [sym_let_binding] = STATE(79),
    [sym_ite_binding] = STATE(79),
    [sym_flip] = STATE(79),
    [sym_observe] = STATE(79),
    [sym_sample] = STATE(79),
    [sym_bool] = STATE(43),
    [sym__value] = STATE(43),
    [sym_anf] = STATE(51),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
  [6] = {
    [sym__expr] = STATE(66),
    [sym_let_binding] = STATE(66),
    [sym_ite_binding] = STATE(66),
    [sym_flip] = STATE(66),
    [sym_observe] = STATE(66),
    [sym_sample] = STATE(66),
    [sym_bool] = STATE(43),
    [sym__value] = STATE(43),
    [sym_anf] = STATE(51),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
  [7] = {
    [sym__expr] = STATE(65),
    [sym_let_binding] = STATE(65),
    [sym_ite_binding] = STATE(65),
    [sym_flip] = STATE(65),
    [sym_observe] = STATE(65),
    [sym_sample] = STATE(65),
    [sym_bool] = STATE(43),
    [sym__value] = STATE(43),
    [sym_anf] = STATE(51),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
  [8] = {
    [sym__expr] = STATE(91),
    [sym_let_binding] = STATE(91),
    [sym_ite_binding] = STATE(91),
    [sym_flip] = STATE(91),
    [sym_observe] = STATE(91),
    [sym_sample] = STATE(91),
    [sym_bool] = STATE(43),
    [sym__value] = STATE(43),
    [sym_anf] = STATE(51),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
  [9] = {
    [sym__expr] = STATE(24),
    [sym_let_binding] = STATE(24),
    [sym_ite_binding] = STATE(24),
    [sym_flip] = STATE(24),
    [sym_observe] = STATE(24),
    [sym_sample] = STATE(24),
    [sym_bool] = STATE(20),
    [sym__value] = STATE(20),
    [sym_anf] = STATE(19),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_fst] = ACTIONS(25),
    [anon_sym_snd] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_flip] = ACTIONS(35),
    [anon_sym_observe] = ACTIONS(37),
    [anon_sym_sample] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [sym_bool_unop] = ACTIONS(43),
  },
  [10] = {
    [sym__expr] = STATE(3),
    [sym_let_binding] = STATE(3),
    [sym_ite_binding] = STATE(3),
    [sym_flip] = STATE(3),
    [sym_observe] = STATE(3),
    [sym_sample] = STATE(3),
    [sym_bool] = STATE(20),
    [sym__value] = STATE(20),
    [sym_anf] = STATE(19),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_fst] = ACTIONS(25),
    [anon_sym_snd] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_flip] = ACTIONS(35),
    [anon_sym_observe] = ACTIONS(37),
    [anon_sym_sample] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [sym_bool_unop] = ACTIONS(43),
  },
  [11] = {
    [sym__expr] = STATE(29),
    [sym_let_binding] = STATE(29),
    [sym_ite_binding] = STATE(29),
    [sym_flip] = STATE(29),
    [sym_observe] = STATE(29),
    [sym_sample] = STATE(29),
    [sym_bool] = STATE(20),
    [sym__value] = STATE(20),
    [sym_anf] = STATE(19),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_fst] = ACTIONS(25),
    [anon_sym_snd] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_flip] = ACTIONS(35),
    [anon_sym_observe] = ACTIONS(37),
    [anon_sym_sample] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [sym_bool_unop] = ACTIONS(43),
  },
  [12] = {
    [sym__expr] = STATE(77),
    [sym_let_binding] = STATE(77),
    [sym_ite_binding] = STATE(77),
    [sym_flip] = STATE(77),
    [sym_observe] = STATE(77),
    [sym_sample] = STATE(77),
    [sym_bool] = STATE(43),
    [sym__value] = STATE(43),
    [sym_anf] = STATE(51),
    [sym_identifier] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
  [13] = {
    [sym__expr] = STATE(2),
    [sym_let_binding] = STATE(2),
    [sym_ite_binding] = STATE(2),
    [sym_flip] = STATE(2),
    [sym_observe] = STATE(2),
    [sym_sample] = STATE(2),
    [sym_bool] = STATE(20),
    [sym__value] = STATE(20),
    [sym_anf] = STATE(19),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_fst] = ACTIONS(25),
    [anon_sym_snd] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(33),
    [anon_sym_flip] = ACTIONS(35),
    [anon_sym_observe] = ACTIONS(37),
    [anon_sym_sample] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(41),
    [anon_sym_false] = ACTIONS(41),
    [sym_bool_unop] = ACTIONS(43),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    STATE(82), 1,
      sym_float_op,
    ACTIONS(49), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(51), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [27] = 4,
    STATE(46), 1,
      sym_bool_biop,
    ACTIONS(55), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(53), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [52] = 3,
    STATE(46), 1,
      sym_bool_biop,
    ACTIONS(61), 4,
      anon_sym_LPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      sym_bool_unop,
    ACTIONS(59), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [75] = 3,
    STATE(46), 1,
      sym_bool_biop,
    ACTIONS(65), 4,
      anon_sym_LPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      sym_bool_unop,
    ACTIONS(63), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [98] = 4,
    STATE(46), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(69), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(67), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [123] = 4,
    STATE(46), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(73), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(71), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [148] = 2,
    ACTIONS(77), 4,
      anon_sym_LPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      sym_bool_unop,
    ACTIONS(75), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [168] = 2,
    ACTIONS(81), 4,
      anon_sym_LPAREN,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      sym_bool_unop,
    ACTIONS(79), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [188] = 2,
    ACTIONS(85), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(83), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [206] = 2,
    ACTIONS(89), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(87), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [224] = 2,
    ACTIONS(93), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(91), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [242] = 2,
    ACTIONS(97), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(95), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [260] = 2,
    ACTIONS(101), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(99), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [278] = 2,
    ACTIONS(105), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(103), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [296] = 2,
    ACTIONS(109), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(107), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [314] = 2,
    ACTIONS(113), 2,
      anon_sym_LPAREN,
      sym_bool_unop,
    ACTIONS(111), 11,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_if,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [332] = 3,
    STATE(90), 1,
      sym_float_op,
    ACTIONS(49), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
    ACTIONS(51), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
  [347] = 2,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(65), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [360] = 6,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_bool_unop,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    STATE(18), 1,
      sym_anf,
    ACTIONS(41), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_bool,
      sym__value,
  [381] = 6,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
    STATE(53), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [402] = 2,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(61), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [415] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(60), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [433] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(61), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [451] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(59), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [469] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(57), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [487] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(56), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [505] = 5,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_bool_unop,
    STATE(15), 1,
      sym_anf,
    ACTIONS(41), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_bool,
      sym__value,
  [523] = 1,
    ACTIONS(81), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [533] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(31), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [551] = 1,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_then,
      anon_sym_else,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [561] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(52), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [579] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(62), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [597] = 5,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_bool_unop,
    STATE(16), 1,
      sym_anf,
    ACTIONS(41), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_bool,
      sym__value,
  [615] = 5,
    ACTIONS(23), 1,
      sym_identifier,
    ACTIONS(43), 1,
      sym_bool_unop,
    STATE(17), 1,
      sym_anf,
    ACTIONS(41), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_bool,
      sym__value,
  [633] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(58), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [651] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(55), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [669] = 5,
    ACTIONS(3), 1,
      sym_identifier,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(34), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(43), 2,
      sym_bool,
      sym__value,
  [687] = 3,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(73), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [700] = 3,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [713] = 3,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(69), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [726] = 2,
    ACTIONS(121), 1,
      sym_bool_unop,
    ACTIONS(119), 3,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
  [735] = 3,
    ACTIONS(123), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [746] = 3,
    ACTIONS(125), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [757] = 3,
    ACTIONS(127), 1,
      anon_sym_then,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [768] = 3,
    ACTIONS(129), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [779] = 3,
    ACTIONS(131), 1,
      anon_sym_then,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [790] = 3,
    ACTIONS(133), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [801] = 3,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [812] = 3,
    ACTIONS(137), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_bool_biop,
    ACTIONS(57), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [823] = 1,
    ACTIONS(89), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [829] = 3,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
    ACTIONS(141), 1,
      sym_float,
    STATE(88), 1,
      sym__float,
  [839] = 1,
    ACTIONS(93), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [845] = 1,
    ACTIONS(113), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [851] = 1,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [857] = 1,
    ACTIONS(105), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [863] = 1,
    ACTIONS(101), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [869] = 1,
    ACTIONS(97), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [875] = 3,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_float,
    STATE(23), 1,
      sym__float,
  [885] = 3,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
    ACTIONS(141), 1,
      sym_float,
    STATE(63), 1,
      sym__float,
  [895] = 1,
    ACTIONS(85), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_else,
  [901] = 3,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
    ACTIONS(141), 1,
      sym_float,
    STATE(81), 1,
      sym__float,
  [911] = 1,
    ACTIONS(147), 1,
      ts_builtin_sym_end,
  [915] = 1,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
  [919] = 1,
    ACTIONS(151), 1,
      anon_sym_RPAREN,
  [923] = 1,
    ACTIONS(153), 1,
      anon_sym_LPAREN,
  [927] = 1,
    ACTIONS(155), 1,
      anon_sym_else,
  [931] = 1,
    ACTIONS(157), 1,
      anon_sym_EQ,
  [935] = 1,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
  [939] = 1,
    ACTIONS(159), 1,
      sym_float,
  [943] = 1,
    ACTIONS(161), 1,
      sym_identifier,
  [947] = 1,
    ACTIONS(163), 1,
      anon_sym_RPAREN,
  [951] = 1,
    ACTIONS(165), 1,
      anon_sym_EQ,
  [955] = 1,
    ACTIONS(167), 1,
      sym_identifier,
  [959] = 1,
    ACTIONS(169), 1,
      anon_sym_LPAREN,
  [963] = 1,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
  [967] = 1,
    ACTIONS(173), 1,
      sym_float,
  [971] = 1,
    ACTIONS(171), 1,
      sym_float,
  [975] = 1,
    ACTIONS(175), 1,
      anon_sym_else,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 27,
  [SMALL_STATE(16)] = 52,
  [SMALL_STATE(17)] = 75,
  [SMALL_STATE(18)] = 98,
  [SMALL_STATE(19)] = 123,
  [SMALL_STATE(20)] = 148,
  [SMALL_STATE(21)] = 168,
  [SMALL_STATE(22)] = 188,
  [SMALL_STATE(23)] = 206,
  [SMALL_STATE(24)] = 224,
  [SMALL_STATE(25)] = 242,
  [SMALL_STATE(26)] = 260,
  [SMALL_STATE(27)] = 278,
  [SMALL_STATE(28)] = 296,
  [SMALL_STATE(29)] = 314,
  [SMALL_STATE(30)] = 332,
  [SMALL_STATE(31)] = 347,
  [SMALL_STATE(32)] = 360,
  [SMALL_STATE(33)] = 381,
  [SMALL_STATE(34)] = 402,
  [SMALL_STATE(35)] = 415,
  [SMALL_STATE(36)] = 433,
  [SMALL_STATE(37)] = 451,
  [SMALL_STATE(38)] = 469,
  [SMALL_STATE(39)] = 487,
  [SMALL_STATE(40)] = 505,
  [SMALL_STATE(41)] = 523,
  [SMALL_STATE(42)] = 533,
  [SMALL_STATE(43)] = 551,
  [SMALL_STATE(44)] = 561,
  [SMALL_STATE(45)] = 579,
  [SMALL_STATE(46)] = 597,
  [SMALL_STATE(47)] = 615,
  [SMALL_STATE(48)] = 633,
  [SMALL_STATE(49)] = 651,
  [SMALL_STATE(50)] = 669,
  [SMALL_STATE(51)] = 687,
  [SMALL_STATE(52)] = 700,
  [SMALL_STATE(53)] = 713,
  [SMALL_STATE(54)] = 726,
  [SMALL_STATE(55)] = 735,
  [SMALL_STATE(56)] = 746,
  [SMALL_STATE(57)] = 757,
  [SMALL_STATE(58)] = 768,
  [SMALL_STATE(59)] = 779,
  [SMALL_STATE(60)] = 790,
  [SMALL_STATE(61)] = 801,
  [SMALL_STATE(62)] = 812,
  [SMALL_STATE(63)] = 823,
  [SMALL_STATE(64)] = 829,
  [SMALL_STATE(65)] = 839,
  [SMALL_STATE(66)] = 845,
  [SMALL_STATE(67)] = 851,
  [SMALL_STATE(68)] = 857,
  [SMALL_STATE(69)] = 863,
  [SMALL_STATE(70)] = 869,
  [SMALL_STATE(71)] = 875,
  [SMALL_STATE(72)] = 885,
  [SMALL_STATE(73)] = 895,
  [SMALL_STATE(74)] = 901,
  [SMALL_STATE(75)] = 911,
  [SMALL_STATE(76)] = 915,
  [SMALL_STATE(77)] = 919,
  [SMALL_STATE(78)] = 923,
  [SMALL_STATE(79)] = 927,
  [SMALL_STATE(80)] = 931,
  [SMALL_STATE(81)] = 935,
  [SMALL_STATE(82)] = 939,
  [SMALL_STATE(83)] = 943,
  [SMALL_STATE(84)] = 947,
  [SMALL_STATE(85)] = 951,
  [SMALL_STATE(86)] = 955,
  [SMALL_STATE(87)] = 959,
  [SMALL_STATE(88)] = 963,
  [SMALL_STATE(89)] = 967,
  [SMALL_STATE(90)] = 971,
  [SMALL_STATE(91)] = 975,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 2),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 2),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anf, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anf, 3),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anf, 2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anf, 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_observe, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observe, 2),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_anf, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anf, 1),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__float, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 3),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flip, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flip, 2),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ite_binding, 6),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ite_binding, 6),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_observe, 4),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observe, 4),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sample, 4),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 4),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expr, 5),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 5),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_binding, 5),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 5),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_binding, 6),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 6),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool_biop, 1),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_biop, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [149] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_op, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_weight4me(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
