#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum {
  sym_identifier = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  sym_tBool = 4,
  anon_sym_COMMA = 5,
  anon_sym_fst = 6,
  anon_sym_snd = 7,
  anon_sym_let = 8,
  anon_sym_COLON = 9,
  anon_sym_EQ = 10,
  anon_sym_in = 11,
  anon_sym_SEMI = 12,
  anon_sym_if = 13,
  anon_sym_then = 14,
  anon_sym_else = 15,
  anon_sym_flip = 16,
  anon_sym_observe = 17,
  anon_sym_sample = 18,
  anon_sym_true = 19,
  anon_sym_false = 20,
  anon_sym_PIPE_PIPE = 21,
  anon_sym_AMP_AMP = 22,
  sym_bool_unop = 23,
  sym_float = 24,
  anon_sym_STAR = 25,
  anon_sym_SLASH = 26,
  anon_sym_PLUS = 27,
  anon_sym_DASH = 28,
  sym_source_file = 29,
  sym__expr = 30,
  sym_ty = 31,
  sym_tProd = 32,
  sym_fst = 33,
  sym_snd = 34,
  sym_prod = 35,
  sym_let_binding = 36,
  sym_ite_binding = 37,
  sym_flip = 38,
  sym_observe = 39,
  sym_sample = 40,
  sym_bool = 41,
  sym_bool_biop = 42,
  sym__float = 43,
  sym_float_op = 44,
  sym__value = 45,
  sym_ann = 46,
  sym_anf = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_tBool] = "tBool",
  [anon_sym_COMMA] = ",",
  [anon_sym_fst] = "fst",
  [anon_sym_snd] = "snd",
  [anon_sym_let] = "let",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_in] = "in",
  [anon_sym_SEMI] = ";",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_flip] = "flip",
  [anon_sym_observe] = "observe",
  [anon_sym_sample] = "sample",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [sym_bool_unop] = "bool_unop",
  [sym_float] = "float",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [sym_source_file] = "source_file",
  [sym__expr] = "_expr",
  [sym_ty] = "ty",
  [sym_tProd] = "tProd",
  [sym_fst] = "fst",
  [sym_snd] = "snd",
  [sym_prod] = "prod",
  [sym_let_binding] = "let_binding",
  [sym_ite_binding] = "ite_binding",
  [sym_flip] = "flip",
  [sym_observe] = "observe",
  [sym_sample] = "sample",
  [sym_bool] = "bool",
  [sym_bool_biop] = "bool_biop",
  [sym__float] = "_float",
  [sym_float_op] = "float_op",
  [sym__value] = "_value",
  [sym_ann] = "ann",
  [sym_anf] = "anf",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_tBool] = sym_tBool,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_fst] = anon_sym_fst,
  [anon_sym_snd] = anon_sym_snd,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_flip] = anon_sym_flip,
  [anon_sym_observe] = anon_sym_observe,
  [anon_sym_sample] = anon_sym_sample,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [sym_bool_unop] = sym_bool_unop,
  [sym_float] = sym_float,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_source_file] = sym_source_file,
  [sym__expr] = sym__expr,
  [sym_ty] = sym_ty,
  [sym_tProd] = sym_tProd,
  [sym_fst] = sym_fst,
  [sym_snd] = sym_snd,
  [sym_prod] = sym_prod,
  [sym_let_binding] = sym_let_binding,
  [sym_ite_binding] = sym_ite_binding,
  [sym_flip] = sym_flip,
  [sym_observe] = sym_observe,
  [sym_sample] = sym_sample,
  [sym_bool] = sym_bool,
  [sym_bool_biop] = sym_bool_biop,
  [sym__float] = sym__float,
  [sym_float_op] = sym_float_op,
  [sym__value] = sym__value,
  [sym_ann] = sym_ann,
  [sym_anf] = sym_anf,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_tBool] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fst] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_snd] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_observe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sample] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [sym_bool_unop] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expr] = {
    .visible = false,
    .named = true,
  },
  [sym_ty] = {
    .visible = true,
    .named = true,
  },
  [sym_tProd] = {
    .visible = true,
    .named = true,
  },
  [sym_fst] = {
    .visible = true,
    .named = true,
  },
  [sym_snd] = {
    .visible = true,
    .named = true,
  },
  [sym_prod] = {
    .visible = true,
    .named = true,
  },
  [sym_let_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_ite_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_flip] = {
    .visible = true,
    .named = true,
  },
  [sym_observe] = {
    .visible = true,
    .named = true,
  },
  [sym_sample] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_bool_biop] = {
    .visible = true,
    .named = true,
  },
  [sym__float] = {
    .visible = false,
    .named = true,
  },
  [sym_float_op] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_ann] = {
    .visible = true,
    .named = true,
  },
  [sym_anf] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '!') ADVANCE(12);
      if (lookahead == '&') ADVANCE(1);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == ')') ADVANCE(5);
      if (lookahead == '*') ADVANCE(15);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(6);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead == '/') ADVANCE(16);
      if (lookahead == ':') ADVANCE(7);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '|') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 1:
      if (lookahead == '&') ADVANCE(11);
      END_STATE();
    case 2:
      if (lookahead == '|') ADVANCE(10);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_bool_unop);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '.') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'B') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'l') ADVANCE(5);
      if (lookahead == 'o') ADVANCE(6);
      if (lookahead == 's') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(12);
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'f') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'h') ADVANCE(20);
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'm') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'd') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 's') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_fst);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_snd);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(39);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_tBool);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_flip);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 42:
      if (lookahead == 'v') ADVANCE(44);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_sample);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_observe);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_tBool] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_fst] = ACTIONS(1),
    [anon_sym_snd] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_flip] = ACTIONS(1),
    [anon_sym_observe] = ACTIONS(1),
    [anon_sym_sample] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [sym_bool_unop] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(61),
    [sym__expr] = STATE(52),
    [sym_fst] = STATE(52),
    [sym_snd] = STATE(52),
    [sym_prod] = STATE(52),
    [sym_let_binding] = STATE(52),
    [sym_ite_binding] = STATE(52),
    [sym_flip] = STATE(52),
    [sym_observe] = STATE(52),
    [sym_sample] = STATE(52),
    [sym_bool] = STATE(12),
    [sym__value] = STATE(12),
    [sym_ann] = STATE(52),
    [sym_anf] = STATE(15),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
  [2] = {
    [sym__expr] = STATE(26),
    [sym_fst] = STATE(26),
    [sym_snd] = STATE(26),
    [sym_prod] = STATE(26),
    [sym_let_binding] = STATE(26),
    [sym_ite_binding] = STATE(26),
    [sym_flip] = STATE(26),
    [sym_observe] = STATE(26),
    [sym_sample] = STATE(26),
    [sym_bool] = STATE(12),
    [sym__value] = STATE(12),
    [sym_ann] = STATE(26),
    [sym_anf] = STATE(15),
    [anon_sym_LPAREN] = ACTIONS(3),
    [anon_sym_fst] = ACTIONS(5),
    [anon_sym_snd] = ACTIONS(7),
    [anon_sym_let] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(23),
    [anon_sym_in] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_if] = ACTIONS(11),
    [anon_sym_flip] = ACTIONS(13),
    [anon_sym_observe] = ACTIONS(15),
    [anon_sym_sample] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_bool_unop] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_fst,
    ACTIONS(7), 1,
      anon_sym_snd,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_flip,
    ACTIONS(15), 1,
      anon_sym_observe,
    ACTIONS(17), 1,
      anon_sym_sample,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(35), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
    STATE(51), 10,
      sym__expr,
      sym_fst,
      sym_snd,
      sym_prod,
      sym_let_binding,
      sym_ite_binding,
      sym_flip,
      sym_observe,
      sym_sample,
      sym_ann,
  [51] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_fst,
    ACTIONS(7), 1,
      anon_sym_snd,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_flip,
    ACTIONS(15), 1,
      anon_sym_observe,
    ACTIONS(17), 1,
      anon_sym_sample,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(15), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
    STATE(49), 10,
      sym__expr,
      sym_fst,
      sym_snd,
      sym_prod,
      sym_let_binding,
      sym_ite_binding,
      sym_flip,
      sym_observe,
      sym_sample,
      sym_ann,
  [102] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_fst,
    ACTIONS(7), 1,
      anon_sym_snd,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_flip,
    ACTIONS(15), 1,
      anon_sym_observe,
    ACTIONS(17), 1,
      anon_sym_sample,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(15), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
    STATE(50), 10,
      sym__expr,
      sym_fst,
      sym_snd,
      sym_prod,
      sym_let_binding,
      sym_ite_binding,
      sym_flip,
      sym_observe,
      sym_sample,
      sym_ann,
  [153] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_fst,
    ACTIONS(7), 1,
      anon_sym_snd,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_flip,
    ACTIONS(15), 1,
      anon_sym_observe,
    ACTIONS(17), 1,
      anon_sym_sample,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(15), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
    STATE(2), 10,
      sym__expr,
      sym_fst,
      sym_snd,
      sym_prod,
      sym_let_binding,
      sym_ite_binding,
      sym_flip,
      sym_observe,
      sym_sample,
      sym_ann,
  [204] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_fst,
    ACTIONS(7), 1,
      anon_sym_snd,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_flip,
    ACTIONS(15), 1,
      anon_sym_observe,
    ACTIONS(17), 1,
      anon_sym_sample,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(15), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
    STATE(24), 10,
      sym__expr,
      sym_fst,
      sym_snd,
      sym_prod,
      sym_let_binding,
      sym_ite_binding,
      sym_flip,
      sym_observe,
      sym_sample,
      sym_ann,
  [255] = 13,
    ACTIONS(3), 1,
      anon_sym_LPAREN,
    ACTIONS(5), 1,
      anon_sym_fst,
    ACTIONS(7), 1,
      anon_sym_snd,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_if,
    ACTIONS(13), 1,
      anon_sym_flip,
    ACTIONS(15), 1,
      anon_sym_observe,
    ACTIONS(17), 1,
      anon_sym_sample,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(15), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
    STATE(20), 10,
      sym__expr,
      sym_fst,
      sym_snd,
      sym_prod,
      sym_let_binding,
      sym_ite_binding,
      sym_flip,
      sym_observe,
      sym_sample,
      sym_ann,
  [306] = 2,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(27), 21,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      sym_bool_unop,
  [333] = 2,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(29), 21,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      sym_bool_unop,
  [360] = 3,
    STATE(54), 1,
      sym_float_op,
    ACTIONS(33), 4,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [389] = 1,
    ACTIONS(35), 21,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      sym_bool_unop,
  [413] = 1,
    ACTIONS(37), 21,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_then,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      sym_bool_unop,
  [437] = 3,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(41), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(39), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [464] = 3,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(41), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(43), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [491] = 3,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(41), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(45), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [518] = 3,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(41), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(47), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [545] = 1,
    ACTIONS(49), 19,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [567] = 1,
    ACTIONS(51), 19,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [589] = 2,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(53), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [611] = 1,
    ACTIONS(55), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [631] = 1,
    ACTIONS(57), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [651] = 1,
    ACTIONS(59), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [671] = 2,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(61), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [693] = 1,
    ACTIONS(63), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [713] = 2,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(65), 16,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [735] = 1,
    ACTIONS(67), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [755] = 1,
    ACTIONS(69), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [775] = 1,
    ACTIONS(71), 17,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_fst,
      anon_sym_snd,
      anon_sym_let,
      anon_sym_COLON,
      anon_sym_in,
      anon_sym_SEMI,
      anon_sym_if,
      anon_sym_else,
      anon_sym_flip,
      anon_sym_observe,
      anon_sym_sample,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [795] = 5,
    ACTIONS(21), 1,
      sym_bool_unop,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    STATE(17), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
  [813] = 4,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(10), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
  [828] = 4,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(43), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
  [843] = 4,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(45), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
  [858] = 4,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(9), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
  [873] = 4,
    ACTIONS(75), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(41), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
    ACTIONS(43), 2,
      anon_sym_RPAREN,
      anon_sym_COLON,
  [888] = 4,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(44), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
  [903] = 4,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(16), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
  [918] = 4,
    ACTIONS(21), 1,
      sym_bool_unop,
    STATE(14), 1,
      sym_anf,
    ACTIONS(19), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_bool,
      sym__value,
  [933] = 4,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(79), 1,
      sym_tBool,
    STATE(18), 1,
      sym_tProd,
    STATE(23), 1,
      sym_ty,
  [946] = 4,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(79), 1,
      sym_tBool,
    STATE(18), 1,
      sym_tProd,
    STATE(60), 1,
      sym_ty,
  [959] = 4,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(79), 1,
      sym_tBool,
    STATE(18), 1,
      sym_tProd,
    STATE(57), 1,
      sym_ty,
  [972] = 4,
    ACTIONS(77), 1,
      anon_sym_LPAREN,
    ACTIONS(79), 1,
      sym_tBool,
    STATE(18), 1,
      sym_tProd,
    STATE(53), 1,
      sym_ty,
  [985] = 3,
    ACTIONS(81), 1,
      anon_sym_then,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(41), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [996] = 3,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(41), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1007] = 3,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_bool_biop,
    ACTIONS(41), 2,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [1018] = 1,
    ACTIONS(87), 3,
      anon_sym_true,
      anon_sym_false,
      sym_bool_unop,
  [1024] = 3,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      sym_float,
    STATE(58), 1,
      sym__float,
  [1034] = 3,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      sym_float,
    STATE(27), 1,
      sym__float,
  [1044] = 2,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_else,
  [1051] = 2,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
  [1058] = 2,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
  [1065] = 2,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
  [1072] = 1,
    ACTIONS(101), 1,
      anon_sym_EQ,
  [1076] = 1,
    ACTIONS(103), 1,
      sym_float,
  [1080] = 1,
    ACTIONS(105), 1,
      sym_float,
  [1084] = 1,
    ACTIONS(107), 1,
      sym_identifier,
  [1088] = 1,
    ACTIONS(109), 1,
      anon_sym_COMMA,
  [1092] = 1,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
  [1096] = 1,
    ACTIONS(111), 1,
      anon_sym_COLON,
  [1100] = 1,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
  [1104] = 1,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
  [1108] = 1,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 51,
  [SMALL_STATE(5)] = 102,
  [SMALL_STATE(6)] = 153,
  [SMALL_STATE(7)] = 204,
  [SMALL_STATE(8)] = 255,
  [SMALL_STATE(9)] = 306,
  [SMALL_STATE(10)] = 333,
  [SMALL_STATE(11)] = 360,
  [SMALL_STATE(12)] = 389,
  [SMALL_STATE(13)] = 413,
  [SMALL_STATE(14)] = 437,
  [SMALL_STATE(15)] = 464,
  [SMALL_STATE(16)] = 491,
  [SMALL_STATE(17)] = 518,
  [SMALL_STATE(18)] = 545,
  [SMALL_STATE(19)] = 567,
  [SMALL_STATE(20)] = 589,
  [SMALL_STATE(21)] = 611,
  [SMALL_STATE(22)] = 631,
  [SMALL_STATE(23)] = 651,
  [SMALL_STATE(24)] = 671,
  [SMALL_STATE(25)] = 693,
  [SMALL_STATE(26)] = 713,
  [SMALL_STATE(27)] = 735,
  [SMALL_STATE(28)] = 755,
  [SMALL_STATE(29)] = 775,
  [SMALL_STATE(30)] = 795,
  [SMALL_STATE(31)] = 813,
  [SMALL_STATE(32)] = 828,
  [SMALL_STATE(33)] = 843,
  [SMALL_STATE(34)] = 858,
  [SMALL_STATE(35)] = 873,
  [SMALL_STATE(36)] = 888,
  [SMALL_STATE(37)] = 903,
  [SMALL_STATE(38)] = 918,
  [SMALL_STATE(39)] = 933,
  [SMALL_STATE(40)] = 946,
  [SMALL_STATE(41)] = 959,
  [SMALL_STATE(42)] = 972,
  [SMALL_STATE(43)] = 985,
  [SMALL_STATE(44)] = 996,
  [SMALL_STATE(45)] = 1007,
  [SMALL_STATE(46)] = 1018,
  [SMALL_STATE(47)] = 1024,
  [SMALL_STATE(48)] = 1034,
  [SMALL_STATE(49)] = 1044,
  [SMALL_STATE(50)] = 1051,
  [SMALL_STATE(51)] = 1058,
  [SMALL_STATE(52)] = 1065,
  [SMALL_STATE(53)] = 1072,
  [SMALL_STATE(54)] = 1076,
  [SMALL_STATE(55)] = 1080,
  [SMALL_STATE(56)] = 1084,
  [SMALL_STATE(57)] = 1088,
  [SMALL_STATE(58)] = 1092,
  [SMALL_STATE(59)] = 1096,
  [SMALL_STATE(60)] = 1100,
  [SMALL_STATE(61)] = 1104,
  [SMALL_STATE(62)] = 1108,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anf, 3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anf, 2),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anf, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fst, 2),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_snd, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observe, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ty, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tProd, 5),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 8),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__float, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_observe, 4),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ann, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ite_binding, 6),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prod, 5),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 7),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flip, 2),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sample, 4),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expr, 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool_biop, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_op, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_yodel(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
